In [2]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv('../data/movies_metadata.csv')

# Display
df.head()

/Users/jyang03/.virtualenvs/ds/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2705: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [25]:
#Calculate the number of votes garnered by the 80th percentile movie
m = df['vote_count'].quantile(0.98)
m

1236.8199999999997

In [26]:
q_movies = df[(df['runtime'] >= 45) & (df['runtime'] <= 300)]
q_movies = q_movies[q_movies['vote_count'] >= m]

q_movies.shape

(910, 24)

In [21]:
C = df['vote_average'].mean()
C

5.618207215134185

In [12]:
def weighted_rating(x, m=m, C=C):
    v = x['vote_count']
    R = x['vote_average']
    
    return (v/(v + m) * R) + (m/(v+m) * C)

In [27]:
q_movies['score'] = q_movies.apply(weighted_rating, axis=1)

In [28]:
q_movies.sort_values('score', ascending=False).head(250)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,score
314,False,NaN,25000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,278,tt0111161,en,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,...,2.834147e+07,142.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear can hold you prisoner. Hope can set you f...,The Shawshank Redemption,False,8.5,8358.0,8.482863
834,False,"{'id': 230, 'name': 'The Godfather Collection'...",6000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.thegodfather.com/,238,tt0068646,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",...,2.450664e+08,175.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,An offer you can't refuse.,The Godfather,False,8.5,6024.0,8.476278
12481,False,"{'id': 263, 'name': 'The Dark Knight Collectio...",185000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",http://thedarkknight.warnerbros.com/dvdsite/,155,tt0468569,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,...,1.004558e+09,152.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Why So Serious?,The Dark Knight,False,8.3,12269.0,8.289115
2843,False,NaN,63000000,"[{'id': 18, 'name': 'Drama'}]",http://www.foxmovies.com/movies/fight-club,550,tt0137523,en,Fight Club,A ticking-time-bomb insomniac and a slippery s...,...,1.008538e+08,139.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Mischief. Mayhem. Soap.,Fight Club,False,8.3,9678.0,8.286216
292,False,NaN,8000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",NaN,680,tt0110912,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",...,2.139288e+08,154.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Just because you are a character doesn't mean ...,Pulp Fiction,False,8.3,8670.0,8.284623
522,False,NaN,22000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",http://www.schindlerslist.com/,424,tt0108052,en,Schindler's List,The true story of how businessman Oskar Schind...,...,3.213656e+08,195.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,"Whoever saves one life, saves the world entire.",Schindler's List,False,8.3,4436.0,8.270109
23673,False,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,244786,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",...,1.309200e+07,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,False,8.3,4376.0,8.269704
5481,False,NaN,15000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",http://movies.disney.com/spirited-away,129,tt0245429,ja,千と千尋の神隠し,A ten year old girl who wanders away from her ...,...,2.749251e+08,125.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,The tunnel led Chihiro to a mysterious town...,Spirited Away,False,8.3,3968.0,8.266628
2211,False,NaN,20000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,637,tt0118799,it,La vita è bella,A touching story of an Italian book seller of ...,...,2.294000e+08,116.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"An unforgettable fable that proves love, famil...",Life Is Beautiful,False,8.3,3643.0,8.263691
1178,False,"{'id': 230, 'name': 'The Godfather Collection'...",13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",NaN,240,tt0071562,en,The Godfather: Part II,In the continuing saga of the Corleone crime f...,...,4.754284e+07,200.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"I don't feel I have to wipe everybody out, Tom...",The Godfather: Part II,False,8.3,3418.0,8.261335
1152,False,NaN,3000000,"[{'id': 18, 'name': 'Drama'}]",NaN,510,tt0073486,en,One Flew Over the Cuckoo's Nest,While serving time for insanity at a state men...,...,1.089813e+08,133.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"If he's crazy, what does that make you?",One Flew Over the Cuckoo's Nest,False,8.3,3001.0,8.256051
1176,False,"{'id': 119674, 'name': 'Psycho Collection', 'p...",806948,"[{'id': 18, 'name': 'Drama'}, {'id': 27, 'name...",NaN,539,tt0054215,en,Psycho,When larcenous real estate clerk Marion Crane ...,...,3.200000e+07,109.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The master of suspense moves his cameras into ...,Psycho,False,8.3,2405.0,8.245381
351,False,NaN,55000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,13,tt0109830,en,Forrest Gump,A man with a low IQ has accomplished great thi...,...,6.779454e+08,142.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"The world will never be the same, once you've ...",Forrest Gump,False,8.2,8147.0,8.184252
1154,False,"{'id': 10, 'name': 'Star Wars Collection', 'po...",18000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,1891,tt0080684,en,The Empire Strikes Back,"The epic saga continues as Luke Skywalker, in ...",...,5.384000e+08,124.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Adventure Continues...,The Empire Strikes Back,False,8.2,5998.0,8.178656
18465,False,NaN,13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,77338,tt1675434,fr,Intouchables,A true story of two men who should never have ...,...,4.264809e+08,112.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Sometimes you have to reach into someone else'...,The Intouchables,False,8.2,5410.0,8.176357
289,False,NaN,16000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",NaN,101,tt0110413,fr,Léon,"Leon, the top hit man in New York, has earned ...",...,4.528497e+07,110.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"If you want a job done well, hire a professional.",Leon: The Professional,False,8.2,4293.0,8.170276
3030,False,NaN,60000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",http://thegreenmile.warnerbros.com/,497,tt0120689,en,The Green Mile,A supernatural tale set on death row in a Sout...,...,2.846000e+08,189.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,Miracles do happen.,The Green Mile,False,8.2,4166.0,8.169381
1170,False,NaN,25000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.warnerbros.com/goodfellas,769,tt0099685,en,GoodFellas,"The true story of Henry Hill, a half-Irish, ha...",...,4.683639e+07,145.0,"[{'iso_639_1': 'it', 'name': 'Italiano'}, {'is...",Released,Three Decades of Life in the Mafia.,GoodFellas,False,8.2,3211.0,8.160414
2216,False,NaN,20000000,"[{'id': 18, 'name': 'Drama'}]",http://www.historyx.com/,73,tt0120586,en,American History X,Derek Vineyard is paroled after serving 3 year...,...,2.387513e+07,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Some Legacies Must End.,American History X,False,8.2,3120.0,8.159278
1161,False,NaN,350000,"[{'id': 18, 'name': 'Drama'}]",NaN,389,tt0050083,en,12 Angry Men,The defense and the prosecution have rested an...,...,1.000000e+06,96.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Life is in their hands. Death is on their minds.,12 Angry Men,False,8.2,2130.0,8.140785
9698,False,NaN,24000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 16, 'na...",NaN,4935,tt0347149,ja,ハウルの動く城,"When Sophie, a shy young woman, is cursed with...",...,2.347105e+08,119.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,The two lived there,Howl's Moving Castle,False,8.2,2049.0,8.138499
2884,False,NaN,26500000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,128,tt0119698,ja,もののけ姫,"Ashitaka, a prince of the disappearing Ainu tr...",...,1.593753e+08,134.0,"[{'iso_639_1': 'ja', 'name': '日本語'}]",Released,The Fate Of The World Rests On The Courage Of ...,Princess Mononoke,False,8.2,2041.0,8.138264
5878,False,NaN,3300000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://cidadededeus.globo.com/,598,tt0317248,pt,Cidade de Deus,Cidade de Deus is a shantytown that started du...,...,3.064177e+07,130.0,"[{'iso_639_1': 'pt', 'name': 'Português'}]",Released,"If you run you're dead... if you stay, you're ...",City of God,False,8.2,1852.0,8.132130
877,False,NaN,1000000,"[{'id': 18, 'name': 'Drama'}, {'id': 9648, 'na...",NaN,567,tt0047396,en,Rear Window,"Professional photographer L.B. ""Jeff"" Jeffries...",...,3.676431e+07,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It only takes one witness to spoil the perfect...,Rear Window,False,8.2,1531.0,8.118349
15480,False,NaN,160000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",http://inceptionmovie.warnerbros.com/,27205,tt1375666,en,Inception,"Cobb, a skilled thief who commits corporate es...",...,8.255328e+08,148.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Your mind is the scene of the crime.,Inception,False,8.1,14075.0,8.091215
22879,False,NaN,165000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 18, '...",http://www.interstellarmovie.net/,157336,tt0816692,en,Interstellar,Interstellar chronicles the adventures of a gr...,...,6.751200e+08,169.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Mankind was born on Earth. It was never meant ...,Interstellar,False,8.1,11187.0,8.088957
7000,False,"{'id': 119, 'name': 'The Lord of the Rings Col...",94000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://www.lordoftherings.net,122,tt0167260,en,The Lord of the Rings: The Return of the King,Aragorn is revealed as the heir to the ancient...,...,1.118889e+09,201.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The eye of the enemy is moving.,The Lord of the Rings: The Return of the King,False,8.1,8226.0,8.085006
256,False,"{'id': 10, 'name': 'Star Wars Collection', 'po...",11000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 28, '...",http://www.starwars.com/films/star-wars-episod...,11,tt0076759,en,Star Wars,Princess Leia is captured and held hostage by ...,...,7.753980e+08,121.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"A long time ago in a galaxy far, far away...",Star Wars,False,8.1,6778.0,8.081826
46,False,NaN,33000000,"[{'id': 80, 'name': 'Crime'}, {'id': 9648, 'na...",http://www.sevenmovie.com/,807,tt0114369,en,Se7en,Two homicide detectives are on a desperate hun...,...,3.273119e+08,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Seven deadly sins. Seven ways to die.,Se7en,False,8.1,5915.0,8.079197
586,False,"{'id': 9743, 'name': 'The Hannibal Lecter Anth...",19000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,274,tt0102926,en,The Silence of the Lambs,"FBI trainee, Clarice Starling ventures into a ...",...,2.727429e+08,119.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,To enter the mind of a killer she must challen...,The Silence of the Lambs,False,8.1,4549.0,8.073018
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11437,False,NaN,100000000,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,1372,tt0450259,en,Blood Diamond,An ex-mercenary turned smuggler. A Mende fishe...,...,1.708779e+08,143.0,"[{'iso_639_1': 'af', 'name': 'Afrikaans'}, {'i...",Released,It will cost you everything.,Blood Diamond,False,7.4,2344.0,7.362786
11617,False,NaN,12000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",http://www.universalstudiosentertainment.com/h...,4638,tt0425112,en,Hot Fuzz,"Top London cop, PC Nicholas Angel is good. Too...",...,8.057377e+07,121.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Big cops. Small town. Moderate violence.,Hot Fuzz,False,7.4,2252.0,7.361299
11353,False,NaN,76000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",http://www.universalstudiosentertainment.com/c...,9693,tt0206634,en,Children of Men,"In 2027, in a chaotic world in which humans ca...",...,6.995975e+07,109.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The future's a thing of the past.,Children of Men,False,7.4,2120.0,7.358945
29463,False,NaN,25000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 18, 'na...",http://theageofadalinemovie.com,293863,tt1655441,en,The Age of Adaline,After 29-year-old Adaline recovers from a near...,...,6.566328e+07,112.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Love is timeless.,The Age of Adaline,False,7.4,2052.0,7.357617
17125,False,NaN,30000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 35, 'na...",http://www.sonyclassics.com/midnightinparis,59436,tt1605783,en,Midnight in Paris,A romantic comedy about a family traveling to ...,...,1.511192e+08,94.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Midnight in Paris,False,7.4,2049.0,7.357556
4591,False,NaN,0,"[{'id': 27, 'name': 'Horror'}, {'id': 18, 'nam...",NaN,1933,tt0230600,en,The Others,Grace is a religious woman who lives in an old...,...,0.000000e+00,101.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,"Sooner or later she'll see them, then everythi...",The Others,False,7.4,1708.0,7.349323
32757,False,NaN,15000000,"[{'id': 18, 'name': 'Drama'}]",NaN,306819,tt0810819,en,The Danish Girl,When Gerda Wegener asks her husband Einar to f...,...,6.419152e+07,120.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Find the courage to be yourself.,The Danish Girl,False,7.4,1689.0,7.348770
892,False,NaN,2777000,"[{'id': 12, 'name': 'Adventure'}, {'id': 10751...",http://thewizardofoz.warnerbros.com/,630,tt0032138,en,The Wizard of Oz,Young Dorothy finds herself in a magical world...,...,3.375497e+07,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"We're off to see the Wizard, the wonderful Wiz...",The Wizard of Oz,False,7.4,1689.0,7.348770
1896,False,NaN,19000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 35, '...",NaN,9340,tt0089218,en,The Goonies,A young teenager named Mikey Walsh finds an ol...,...,6.150322e+07,114.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"The pirates map, The villainous crooks, The un...",The Goonies,False,7.4,1563.0,7.344768
22206,False,NaN,40000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",http://www.lonesurvivorfilm.com/,193756,tt1091191,en,Lone Survivor,"Based on the failed June 28, 2005 mission ""Ope...",...,1.492956e+08,121.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Based on True Acts of Courage,Lone Survivor,False,7.4,1549.0,7.344284
22043,False,NaN,0,"[{'id': 18, 'name': 'Drama'}]",http://www.thebookthief.com/,203833,tt0816442,en,The Book Thief,While subjected to the horrors of WWII Germany...,...,7.658632e+07,131.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Courage beyond words.,The Book Thief,False,7.4,1528.0,7.343543
12165,False,NaN,100000000,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",http://www.americangangster.net/,4982,tt0765429,en,American Gangster,Following the death of his employer and mentor...,...,2.664650e+08,157.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,There are two sides to the American dream,American Gangster,False,7.4,1527.0,7.343507
1610,False,NaN,53000000,"[{'id': 16, 'name': 'Animation'}, {'id': 10751...",NaN,9444,tt0118617,en,Anastasia,This animated adventure retells the story of t...,...,1.398043e+08,94.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Discover the Adventure Behind the Greatest Mys...,Anastasia,False,7.4,1481.0,7.341810
12368,False,NaN,15000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.filminfocus.com/film/in_bruges,8321,tt0780536,en,In Bruges,"Ray and Ken, two hit men, are in Bruges, Belgi...",...,3.453378e+07,107.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Shoot first. Sightsee later.,In Bruges,False,7.4,1414.0,7.339146
10881,False,NaN,27000000,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",NaN,186,tt0425210,en,Lucky Number Slevin,Slevin is mistakenly put in the middle of a pe...,...,5.630888e+07,110.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Wrong Time. Wrong Place. Wrong Number.,Lucky Number Slevin,False,7.4,1356.0,7.336636
4112,False,NaN,53000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,4133,tt0221027,en,Blow,A boy named George Jung grows up in a struggli...,...,8.328230e+07,124.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Based on a True Story.,Blow,False,7.4,1352.0,7.336455
4180,False,NaN,52500000,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,824,tt0203009,en,Moulin Rouge!,A celebration of love and creative inspiration...,...,1.792134e+08,127.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,No Laws. No Limits. One Rule. Never Fall In Love.,Moulin Rouge!,False,7.4,1348.0,7.336274
4849,False,NaN,21000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,9428,tt0265666,en,The Royal Tenenbaums,An estranged family of former child prodigies ...,...,7.144125e+07,110.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"Family isn’t a word, it’s a sentence.",The Royal Tenenbaums,False,7.4,1317.0,7.334828
10240,False,NaN,39000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",NaN,16320,tt0379786,en,Serenity,When the renegade crew of Serenity agrees to h...,...,3.886946e+07,119.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Can't stop the signal.,Serenity,False,7.4,1287.0,7.333366
26553,False,"{'id': 8945, 'name': 'Mad Max Collection', 'po...",150000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.madmaxmovie.com/,76341,tt1392190,en,Mad Max: Fury Road,An apocalyptic story set in the furthest reach...,...,3.788583e+08,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What a Lovely Day.,Mad Max: Fury Road,False,7.3,9629.0,7.291312
26558,False,"{'id': 86311, 'name': 'The Avengers Collection...",280000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://marvel.com/movies/movie/193/avengers_ag...,99861,tt2395427,en,Avengers: Age of Ultron,When Tony Stark tries to jumpstart a dormant p...,...,1.405404e+09,141.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A New Age Has Come.,Avengers: Age of Ultron,False,7.3,6908.0,7.287915
31865,False,NaN,135000000,"[{'id': 37, 'name': 'Western'}, {'id': 18, 'na...",http://www.foxmovies.com/movies/the-revenant,281957,tt1663202,en,The Revenant,"In the 1820s, a frontiersman, Hugh Glass, sets...",...,5.329505e+08,156.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"(n. One who has returned, as if from the dead.)",The Revenant,False,7.3,6558.0,7.287275
21592,False,NaN,105000000,"[{'id': 878, 'name': 'Science Fiction'}, {'id'...",http://gravitymovie.warnerbros.com/,49047,tt1454468,en,Gravity,"Dr. Ryan Stone, a brilliant medical engineer o...",...,7.163927e+08,91.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Don't Let Go,Gravity,False,7.3,5879.0,7.285817
21025,False,"{'id': 382685, 'name': 'Now You See Me Collect...",75000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",NaN,75656,tt1670345,en,Now You See Me,An FBI agent and an Interpol detective track a...,...,1.176989e+08,115.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,4 amazing magicians. 3 impossible heists. 1 bi...,Now You See Me,False,7.3,5635.0,7.285209
22110,False,"{'id': 386382, 'name': 'Frozen Collection', 'p...",150000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",http://movies.disney.com/frozen,109445,tt2294629,en,Frozen,Young princess Anna of Arendelle dreams about ...,...,1.274219e+09,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Only the act of true love will thaw a frozen h...,Frozen,False,7.3,5440.0,7.284683
16066,False,NaN,13000000,"[{'id': 18, 'name': 'Drama'}, {'id': 53, 'name...",http://www.foxsearchlight.com/blackswan/,44214,tt0947798,en,Black Swan,"A ballet dancer wins the lead in ""Swan Lake"" a...",...,3.278037e+08,108.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,"In the era of personal branding, the scariest ...",Black Swan,False,7.3,4562.0,7.281767